CREATE TABLE IF NOT EXISTS BANK_COMPANY
(
   ID BIGINT auto_increment,
   NAME VARCHAR(255) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BANK_DEPARTMENT
(
   ID BIGINT auto_increment,
   NAME VARCHAR(255) NOT NULL,
   COMPANY_ID BIGINT NOT NULL,
   PRIMARY KEY(ID)
);

ALTER TABLE BANK_DEPARTMENT ADD CONSTRAINT BANK_DEPARTMENT_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES BANK_COMPANY;

INSERT INTO BANK_COMPANY(ID, NAME) VALUES (1, 'Pepsi');
INSERT INTO BANK_COMPANY(ID, NAME) VALUES (2, 'Coca Cola');
INSERT INTO BANK_COMPANY(ID, NAME) VALUES (3, 'Sprite');

INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (1, 'Sales & Marketing', 1);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (2, 'Research & Development', 1);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (3, 'Administration', 1);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (4, 'Human Resources', 2);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (5, 'Sales & Marketing', 3);