CREATE TABLE IF NOT EXISTS BANK_COMPANY
(
   ID BIGINT auto_increment,
   NAME VARCHAR(255) NOT NULL,
   VERSION BIGINT NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BANK_DEPARTMENT
(
   ID BIGINT auto_increment,
   NAME VARCHAR(255) NOT NULL,
   COMPANY_ID BIGINT NOT NULL,
   VERSION BIGINT NOT NULL,
   PRIMARY KEY(ID)
);

ALTER TABLE BANK_DEPARTMENT ADD CONSTRAINT BANK_DEPARTMENT_COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES BANK_COMPANY;

INSERT INTO BANK_COMPANY(ID, NAME, VERSION) VALUES (1, 'Pepsi', 0);
INSERT INTO BANK_COMPANY(ID, NAME, VERSION) VALUES (2, 'Coca Cola', 0);
INSERT INTO BANK_COMPANY(ID, NAME, VERSION) VALUES (3, 'Sprite', 0);

INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID, VERSION) VALUES (1, 'Sales & Marketing', 1, 0);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID, VERSION) VALUES (2, 'Research & Development', 1, 0);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID, VERSION) VALUES (3, 'Administration', 1, 0);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID, VERSION) VALUES (4, 'Human Resources', 2, 0);
INSERT INTO BANK_DEPARTMENT(ID, NAME, COMPANY_ID, VERSION) VALUES (5, 'Sales & Marketing', 3, 0);