MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (0, 'Иван', 'Мельников', 'Игоревич');
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (1, 'Мария', 'Злобина', 'Петровна');
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (2, 'Сергей', 'Игнатов', 'Андреевич');
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (3, 'Петр', 'Федоров', 'Сергеевич');
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (4, 'Руслан', 'Злобин', 'Петрович');
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES (5, 'Маргарита', 'Парфенова', 'Олеговна');

MERGE INTO BANK_ACCOUNT (ID,  BALANCE, USER_ID) VALUES (0, 15.0, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (1, 100000.0, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (2, 50000.0, 1);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (3, 3000.0, 2);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (4, 125.0, 3);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (5, 623.0, 4);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (6, 550.0, 5);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (7, 110.0, 5);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID) VALUES (8, 100.0, 5);