CREATE TABLE IF NOT EXISTS BANK_USER
(
   ID BIGINT auto_increment,
   FIRST_NAME VARCHAR(255) NOT NULL,
   LAST_NAME VARCHAR(255) NOT NULL,
   MIDDLE_NAME VARCHAR(255) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT
(
   ID BIGINT auto_increment,
   BALANCE DOUBLE NOT NULL,
   USER_ID BIGINT(255) NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(USER_ID) REFERENCES BANK_USER(ID)
);

CREATE INDEX IF NOT EXISTS BANK_ACCOUNT_USER_ID_IDX ON BANK_ACCOUNT(USER_ID);