INSERT INTO AUTHORITY(NAME) VALUES
    ('COMPANY_CREATE'),
    ('COMPANY_READ'),
    ('COMPANY_UPDATE'),
    ('COMPANY_DELETE'),
    ('DEPARTMENT_CREATE'),
    ('DEPARTMENT_READ'),
    ('DEPARTMENT_UPDATE'),
    ('DEPARTMENT_DELETE'),
    ('ROLE_COMPANY_READER');