apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.container.namespace}}
  labels:
    app: {{.Values.service.name}}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: {{.Values.container.strategy}}
  selector:
    matchLabels:
      app: {{.Values.service.name}}
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{.Values.service.name}}
        version: latest
    spec:
      imagePullSecrets:
        - name: {{.Values.container.imagePullSecrets}}
      containers:
        - name:  {{.Values.service.name}}
          image:  "{{.Values.docker.user}}/domclick:latest"
          imagePullPolicy: {{.Values.container.imagePullPolicy}}
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          resources:
            requests:
              cpu: {{.Values.container.resources.requests.cpu}}
              memory: {{.Values.container.resources.requests.memory}}
            limits:
              cpu: {{.Values.container.resources.limits.cpu}}
              memory: {{.Values.container.resources.limits.memory}}
          ports:
            - name: http-port
              containerPort: {{.Values.container.ports.appPort}}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{.Values.container.readinessProbe.httpGet}}
              port: {{.Values.container.ports.managementPort}}
            initialDelaySeconds: {{.Values.container.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.container.readinessProbe.periodSeconds}}
            successThreshold: {{.Values.container.readinessProbe.successThreshold}}
            failureThreshold: {{.Values.container.readinessProbe.failureThreshold}}
            timeoutSeconds: {{.Values.container.readinessProbe.timeoutSeconds}}
          livenessProbe:
            httpGet:
              path: {{.Values.container.livenessProbe.httpGet}}
              port: {{.Values.container.ports.managementPort}}
            initialDelaySeconds: {{.Values.container.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.container.livenessProbe.periodSeconds}}
            successThreshold: {{.Values.container.livenessProbe.successThreshold}}
            failureThreshold: {{.Values.container.livenessProbe.failureThreshold}}
            timeoutSeconds: {{.Values.container.livenessProbe.timeoutSeconds}}
