CREATE TABLE AUTHORITY (
   ID                  SERIAL PRIMARY KEY,
   NAME                VARCHAR(255) UNIQUE
);

CREATE TABLE USER_ (
  ID                  SERIAL PRIMARY KEY,
  PASSWORD            VARCHAR(255),
  USER_NAME           VARCHAR(255) UNIQUE,
  ACCOUNT_EXPIRED     BOOLEAN,
  ACCOUNT_LOCKED      BOOLEAN,
  CREDENTIALS_EXPIRED BOOLEAN,
  ENABLED             BOOLEAN
);

CREATE TABLE USERS_AUTHORITIES (
   USER_ID            BIGINT NOT NULL REFERENCES USER_(ID),
   AUTHORITY_ID       BIGINT NOT NULL REFERENCES AUTHORITY(ID),
   PRIMARY KEY        (USER_ID, AUTHORITY_ID)
);