CREATE TABLE IF NOT EXISTS BANK_USER
(
   ID BIGINT auto_increment,
   FIRST_NAME VARCHAR(255) NOT NULL,
   LAST_NAME VARCHAR(255) NOT NULL,
   MIDDLE_NAME VARCHAR(255) NOT NULL,
   VERSION BIGINT NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT
(
   ID BIGINT auto_increment,
   BALANCE DECIMAL(20, 2) NOT NULL,
   USER_ID BIGINT(255) NOT NULL,
   VERSION BIGINT NOT NULL,
   PRIMARY KEY(ID)
);

CREATE INDEX IF NOT EXISTS BANK_ACCOUNT_USER_ID_IDX ON BANK_ACCOUNT(USER_ID);

MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (0, 'Иван', 'Мельников', 'Игоревич', 0);
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (1, 'Мария', 'Злобина', 'Петровна', 0);
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (2, 'Сергей', 'Игнатов', 'Андреевич', 0);
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (3, 'Петр', 'Федоров', 'Сергеевич', 0);
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (4, 'Руслан', 'Злобин', 'Петрович', 0);
MERGE INTO BANK_USER (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, VERSION) VALUES (5, 'Маргарита', 'Парфенова', 'Олеговна', 0);

MERGE INTO BANK_ACCOUNT (ID,  BALANCE, USER_ID, VERSION) VALUES (0, 15.50, 0, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (1, 100000.30, 0, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (2, 50000.25, 1, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (3, 3000.12, 2, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (4, 125.0, 3, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (5, 623.0, 4, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (6, 550.0, 5, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (7, 110.0, 5, 0);
MERGE INTO BANK_ACCOUNT (ID, BALANCE, USER_ID, VERSION) VALUES (8, 100.0, 5, 0);